-- Create Channels Table
create table public.channels (
  id bigint generated by default as identity primary key,
  channel_id text not null unique,
  title text not null,
  thumbnail_url text,
  access_token text, -- Encrypted or plain (secured by RLS)
  refresh_token text,
  token_expiry timestamp with time zone,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_updated timestamp with time zone
);

-- Create Daily Metrics Table
create table public.daily_metrics (
  id bigint generated by default as identity primary key,
  channel_id text not null references public.channels(channel_id) on delete cascade,
  date date not null,
  views bigint default 0,
  likes bigint default 0,
  comments bigint default 0,
  subscribers bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Ensure one row per channel per date
  constraint unique_channel_date unique (channel_id, date)
);

-- Enable Row Level Security (RLS)
alter table public.channels enable row level security;
alter table public.daily_metrics enable row level security;

-- Create Policies (Simple for now: Service Role has full access)
-- In a real app, you'd add policies for authenticated users to see ONLY their own data.
create policy "Anon read access" on public.channels for select using (true);
create policy "Anon read access" on public.daily_metrics for select using (true);
